"""change cols

Revision ID: 9fd6973dafda
Revises: 5938540aeff8
Create Date: 2023-06-02 15:57:30.582472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fd6973dafda'
down_revision = '5938540aeff8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'upcoming')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('upcoming', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
